server:
  port: 8084
#  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: USER-SERVICE

  config:
    import: optional:configserver:http://localhost:8085


#eureka:
#  instance:
#    prefer-ip-address: true
##    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state:  3
        sliding-window-type: COUNT_BASED
  retry:
    instances:
      ratingHotelBreaker:
        max-attempts: 3
        wait-duration: 5s

