spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OrderService
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.microservice.order.event.OrderPlaceEvent
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  application:
    name: order-service
server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:podgorica@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instanceId:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: prometheus