
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
    producer:
      key-deserializer: org.apache.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.service.notification.event.OrderPlaceEvent
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:podgorica@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: prometheus