server:
  port: 8088
#  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085
  profiles:
    default:




#eureka:
#  instance:
#    prefer-ip-address: true
##    instance-id: ${random.value}
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

